### ISSUE TITLE
[14.0] Option to skip the generation of payment

### ISSUE THREAD

**Issue by simgonzalez** [OCA/bank-payment#1043]
**Original problem**
We have some account.payment.order that have between 2000-3000 transactions. The action of confirming the payments that creates payment lines can take up to 10 minutes and then we have a timeout. Those 10 minutes are too much and we can't give that to our customers.

**Feature/Solution**
I'd like an option to allow or not the creation of those payment lines because that's the main things that take a lot of time and in our internal process we don't need the payment lines to work. The option could be either on the payment mode or on the payment order itself.

**Alternatives**
Optimising the process that is difficult to actually do as the main ressource needer is the creation of the object itself.
inherit the module to overwrite the method locally. (Not convenient in case of important update)

**Additional context**
Thanks for the incredible work <3

**Comment by pedrobaeza** [comment]
Not possible, sorry. The same situation would be in the previous workflow when finishing the order. Now, it's done in another part, and it has the advantage of generating already the accounting in draft.

Optimizations should come from Odoo itself in their object `account.payment`.

**Comment by davidwul** [comment]
Just adding some context.
This is for debit order. Account payment is not needed because, the bank don't tell us which withdrawn fails. So we only wait for  when the money comes in and reconcile the out_invoice with.
Adding an option (on the payment order or on the payment mode) to not generate account payment would indeed solve the performance issue. Would this be accepted by the OCA?

On the other end, what can be done to enable optimization , should we raise an issue directly on odoo?

**Comment by pedrobaeza** [comment]
This has nothing to do with the money direction. Odoo core + enterprise does the same with payment and debit orders. The idea of this refactoring is:

- Simplify code, letting Odoo core code to deal with the complexity of reconciliations.
- Allow to handle "in_payment" payment state.
- Pre-generate ASAP the accounting.

**Comment by davidwul** [comment]
You're correct, we have the same issue is with the former odoo oca code. And money direction doesn't change the issue.
The change to come closer to odoo core is really good. 

Let me explain our use case, maybe you might see the issue from a different angle with your odoo knowledge.

We have more than 3000 customers with direct debit. With the actual process (in odoo community) we have two problems:
1. performance to generate (10 min) and validate (10 min) the debit order (perfomance is slightly slower than the previous oca code)
2. when we mark the debit order as uploaded, the invoices related are marked as paid. 
This is an issue because, when our customers phones in to inquiry about theirs payment status, our collegue might say that everything's all right when it's not. (if the debit fails on their account). There are no pain 002 to inform about the status of each withdrawal attempts.

For us, the use for the debit order object is to:
1. inform that the invoice was selected in a debit order
2. create the file for the bank

I don't know if our use case can be served with the odoo community as it is now or if it is very special and not common to other OCA odoo user. 
In that case we should develop our own customization to enable using direct debit. 
What is your advice?

**Comment by pedrobaeza** [comment]
For the point 1, it's true that the performance is now a bit less, but it's because it's doing more things. Going to v16 will improve a lot on this.

For the point 2, we have done this move for covering such case, as we will be able to put the invoices in "In payment" state, and switched to Paid when reconciling the statement. This is what I'm now investigating.

**Comment by davidwul** [comment]
Great regarding the in payment state, this is really a good move. First time I hear about that. 
Looking forward to see that.
Regarding the performance issue, we just moved to 14 from 12. We are unfortunately not ready to go for 16.
We don't have the capacity to improve odoo code so we might try to bypass account.payment while waiting for moving to 16.
If you have a better idea, I would be glad to hear it.
Thanks

**Comment by hhgabelgaard** [comment]
Hi @pedrobaeza 
> 
> For the point 2, we have done this move for covering such case, as we will be able to put the invoices in "In payment" state, and switched to Paid when reconciling the statement. This is what I'm now investigating.

Was there any outcome of your investigating regarding "In Payment" state ?
Thanks

**Comment by pedrobaeza** [comment]
Not yet, sorry. Busy holidays comeback...

**Comment by hhgabelgaard** [comment]
Hi @pedrobaeza 
Do we need more than just having _get_invoice_in_payment_state() return 'in_payment'
That seems to work in a minimal test

Or am I missing something?

**Comment by pedrobaeza** [comment]
Yes, @alexis-via was pointing in that direction. Check #1174
