### ISSUE TITLE
How to make a payment order done with account_banking_payment_export?

### ISSUE THREAD

**Issue by matthieuchoplin** [OCA/bank-payment#135]
Hi,

 I have installed the module account_banking_payment_export and was testing it but I do not understand how to make the "payment order" done. The last state to which I managed to go is "Sent".

I have created a supplier invoice and a payment mode such as:
![selection_036](https://cloud.githubusercontent.com/assets/1380333/6418085/1599c35c-beaa-11e4-9da8-d54ced6c6612.png)

When I make the payment, the invoice associated to the payment order is set to "paid" which is good.
So, according to the module description I should be able to set the state of the payment order to "done" after doing a bank statement reconciliation for this invoice.

But when I go to select the invoices on the bank statement, I cannot find the invoice that I have paid.

Is there something that I am missing?

Else, I was proposing a simpler approach here: https://github.com/OCA/bank-payment/pull/132/files
But closed the PR to avoid duplicated work...

**Comment by sbidoul** [comment]
Hi Matthieu,

When paying the invoice is marked paid because it is reconciled by the move to the transfer account. It is therefore not available anymore for bank statement reconciliation. This is normal.

First, make sure your transfer account is flagged "allow reconciliation".

Then when you receive the bank statement, reconcile it with the transfer account and that will make the payment order move to the done state.

**Comment by matthieuchoplin** [comment]
Thanks for your answer Stephane, I managed to get the payment order done after doing a bank statement reconciliation, like you said.

**Comment by matthieuchoplin** [comment]
I added a test regarding this chat regarding this chat: https://github.com/OCA/bank-payment/pull/136
