### ISSUE TITLE
[15.0] - account_payment_order: post-migration script from v14 to v15 raises IndexError: tuple index out of range

### ISSUE THREAD

**Issue by rrebollo** [OCA/bank-payment#1368]
I'm doing an upgrade from v14 EE to v15 EE at odoo.sh. When I commit the submodules from OCA the upgrade fails at this line:
https://github.com/OCA/bank-payment/blob/4449d96278d7ce53629100446c08bf532e4e99d9/account_payment_order/models/account_payment.py#L68

### These are the relevant parts from the traceback:

`Failed for payment with id 1302: tuple index out of range`
```
Traceback (most recent call last):
  File "/home/odoo/.local/lib/python3.8/site-packages/openupgradelib/openupgrade.py", line 1877, in wrapped_function
    func(
  File "/home/odoo/src/user/OCA/bank-payment/account_payment_order/migrations/15.0.2.0.0/post-migration.py", line 178, in migrate
    create_moves_from_orphan_account_payments(env)
  File "/home/odoo/src/user/OCA/bank-payment/account_payment_order/migrations/15.0.2.0.0/post-migration.py", line 128, in create_moves_from_orphan_account_payments
    payment._synchronize_to_moves(["date"])  # no more changed fields needed
  File "/home/odoo/src/odoo/addons/account/models/account_payment.py", line 874, in _synchronize_to_moves
    line_vals_list = pay._prepare_move_line_default_vals(write_off_line_vals=write_off_line_vals)
  File "/home/odoo/src/user/OCA/bank-payment/account_payment_order/models/account_payment.py", line 68, in _prepare_move_line_default_vals
    vals["date_maturity"] = self.payment_line_ids[0].date
  File "/home/odoo/src/odoo/odoo/models.py", line 5940, in __getitem__
    return self.browse((self._ids[key],))
IndexError: tuple index out of range
```
Of course I tried to find payment with id 1302 but that is the payment that is being created so ... 
### The obvious:
There is a payment with no payment_line_ids that cause the error, So is this a valid scenario or the problem laid in the gathering of the data to create the payments and account entries. 

I can't share the database dump but I'll be happy to debug the problem more deeply if someone suggest how.

**Comment by rrebollo** [comment]
@victoralmau @pedrobaeza @MiquelRForgeFlow git blame says U were involved in these features so any hint???

**Comment by pedrobaeza** [comment]
Your 14.0 database is not totally updated before doing the migration. If so, then this script was executed: https://github.com/OCA/bank-payment/blob/14.0/account_payment_order/migrations/14.0.2.0.0/post-migration.py and the 15.0 part wasn't executed.

**Comment by rrebollo** [comment]
> Your 14.0 database is not totally updated before doing the migration. If so, then this script was executed: https://github.com/OCA/bank-payment/blob/14.0/account_payment_order/migrations/14.0.2.0.0/post-migration.py and the 15.0 part wasn't executed.

I think U are right. I don't remember doing the update before starting the upgrade.  I'll follow your suggestion and I'll be back here with some news.

**Comment by rrebollo** [comment]
> Your 14.0 database is not totally updated before doing the migration. If so, then this script was executed: https://github.com/OCA/bank-payment/blob/14.0/account_payment_order/migrations/14.0.2.0.0/post-migration.py and the 15.0 part wasn't executed.

In deed, U can close this.

**Comment by rrebollo** [comment]
Sorry, closing by myself.

**Comment by dalonsod** [comment]
@pedrobaeza I've faced the same issue, but migrating within v15 CE, from `15.0.1.1.1` addon version.

Not sure, but the problem seems to be similar, at the point error is raised a recently created payment has no payment lines yet... these payments seems to be created later at `post_migration` script by `_insert_payment_line_payment_link()`. Should be that payment lines created before? I don't know if there's any reason that justifies payment lines to be created when migration is about to end and, then, after almost every calculation.

**Comment by pedrobaeza** [comment]
Unless you put the full error and stack trace, I can't tell you.

**Comment by dalonsod** [comment]
Yes, I didn't attach it because it's exactly the same trace error provided here (with another payment id, of course)

**Comment by pedrobaeza** [comment]
Well, I would say the same then. The reason for doing the lines adding in end migration is to get all the inheritance in the payment line generation.

**Comment by dalonsod** [comment]
Yes, I understand that payment lines link should be created at some point. But for payments created by the migration script this link is not set yet when `_prepare_move_line_default_vals` is called, then payment lines (required for new `date_maturity` value calculation, https://github.com/OCA/bank-payment/blob/74b02e4126193094203552ee01a88a2e82196abe/account_payment_order/models/account_payment.py#L68) are not found and an error is raised.

I haven't tested it, but error may not raise if `_insert_payment_line_payment_link()` is called before, within `create_moves_from_orphan_account_payments()` before `_synchronize_to_moves()` is called at https://github.com/OCA/bank-payment/blob/74b02e4126193094203552ee01a88a2e82196abe/account_payment_order/migrations/15.0.2.0.0/post-migration.py#L128C21-L128C42. That's why I asked if there's a concrete reason for linking payment lines at the very end of the process.

I'll test it again moving `_insert_payment_line_payment_link()` call and update information here.

**Comment by dalonsod** [comment]
I've moved `_insert_payment_line_payment_link()` https://github.com/OCA/bank-payment/blob/74b02e4126193094203552ee01a88a2e82196abe/account_payment_order/migrations/15.0.2.0.0/post-migration.py#L183 from the end of post-migration script to one line above `create_moves_from_orphan_account_payments()` line https://github.com/OCA/bank-payment/blob/74b02e4126193094203552ee01a88a2e82196abe/account_payment_order/migrations/15.0.2.0.0/post-migration.py#L178, migration didn't crash and seems to work.

The issue can be reproduced if there's a payment order at `generated` state, that is one of the cases covered by previous `_insert_account_payments()` call: some new payments are created, and they need their payment lines already linked before `create_moves_from_orphan_account_payments()` is called, in order to properly set maturity date for new move lines, or process crashes.

@pedrobaeza if this makes sense, I'll make a PR with it

**Comment by pedrobaeza** [comment]
OK then

**Comment by dalonsod** [comment]
Done, https://github.com/OCA/bank-payment/pull/1483
