### ISSUE TITLE
Unable to install module "account_banking_pain_base"

### ISSUE THREAD

**Issue by davidperezgar** [OCA/bank-payment#235]
Hello, 
I'm getting this error:
Unable to install module "account_banking_pain_base" because an external dependency is not met: No module named unidecode

How can I solve it?

**Comment by sandrafig** [comment]
You should install python-unidecode. If you are in Ubuntu open the terminal and type:
sudo apt-get install python-unidecode

**Comment by davidperezgar** [comment]
I don't know why but it depends of this library xfonts-75dpi that I've uninstalled... another way?

**Comment by beo73** [comment]
Hello,
I amcurrently using odoo 12. I tried to install module " account_banking_pain_base ".

I get the following error message:

Unable to install the module "account_banking_pain_base" because of an external dependency not found: No module named unidecode


I have install python-unidecode and I still have the same error.
Can you please give a help? Thank you in advance

**Comment by Alliasys** [comment]
Hello,
I am having the same error using odoo 13 while installing module "account_banking_pain_base".
"Python library not installed: unidecode"

I installed the unidecode (It was required by an other module I installed previously) but still have the error. 

Please can you help me ?
Thank you
