### ISSUE TITLE
[9.0] account_payment_order: propagate partner to offsetting account when possible

### ISSUE THREAD

**Issue by sbidoul** [OCA/bank-payment#277]
When the transfer move has one move line line per partner, it is useful to propagate the partner to the move line on the offsetting account.

@alexis-via do you agree?

https://github.com/OCA/bank-payment/blob/d2e87f74c04f413a793c7c12ec3d440bda6daf41/account_payment_order/models/account_payment_order.py#L358

**Comment by pedrobaeza** [comment]
:+1: for me

**Comment by alexis-via** [comment]
Mmm, I don't see real arguments against it (only that it doesn't behave the same way for grouped payments and non-grouped payments)... but I don't see real arguments in favor of it either. What real advantage do you see ?
But I'm not against it, you can move ahead.

**Comment by alexis-via** [comment]
Thinking about it more closely: if you write the partner on the move line in the bank account, it means that you will have to identify this partner on the bank statement line in order to reconcile it, which is a bit more work. In the countries where you have the bank account of the supplier/customer on the bank statement line, the partner is auto-detected so it's not more work, but for countries like France where this information is not available, it's a bit more work. Anyway, it's easy to inherit, so I'll be able to always write partner_id=False in the bank account move line if I want, thanks to the prepare methods. So it's not a problem for me if you change this.
