### ISSUE TITLE
Référence Unique de Mandat

### ISSUE THREAD

**Issue by pasgou** [OCA/bank-payment#343]
Trying to use this module, I need to enter existing mandates.
How could we write the RUM we created before using Odoo?
The reference isn't accessible in the creation/modify mode.

**Comment by alexis-via** [comment]
The readonly property for that field is only in the form view. So you have several options;
- import via CSV,
- create via python code
- inherit the form view in a custom module

**Comment by pedrobaeza** [comment]
Alexis, maybe it's not so bad idea to allow to use the technique in other places where the field is required and initialized with a default value like `\`. If you don't change it, then the sequence is used for giving next number. Otherwise, the value is used. You can have manually signed bank mandates with other numeration that you want to create manually (without the complications of CSV import).

**Comment by cypx** [comment]
To allow edit on form view just one line need to be changed

```diff
diff --git a/account_banking_mandate/views/account_banking_mandate_view.xml b/account_banking_mandate/views/account_banking_mandate_view.xml
index a681795..0f3375e 100644
--- a/account_banking_mandate/views/account_banking_mandate_view.xml
+++ b/account_banking_mandate/views/account_banking_mandate_view.xml
@@ -25,9 +25,7 @@
             <sheet>
                 <div class="oe_title">
                     <h1>
-                        <field name="unique_mandate_reference"
-                               class="oe_inline"
-                               readonly="1"/>
+                        <field name="unique_mandate_reference" class="oe_inline"/>
                     </h1>
                 </div>
                 <group name="main">
```

**Comment by pedrobaeza** [comment]
Not only that, but make sure a default is provided and retrieve sequence if there's that default. You can do the PR if you consider this interesting.
