### ISSUE TITLE
Partial payment in order

### ISSUE THREAD

**Issue by qpeyramale** [OCA/bank-payment#388]
Hello

I tried to do a partial payment in a debit order with multiple invoices of the same partner, but the partial amount doesn't link to the right invoice.
Debit Order:
![image](https://user-images.githubusercontent.com/7935472/30054949-235901a6-922e-11e7-9af5-c1012d3174d0.png)
Result:
![image](https://user-images.githubusercontent.com/7935472/30054958-299ed810-922e-11e7-956b-bc0cc25c40dc.png)

In the Debit order, I changed the amount of the transaction for the 0007 and at the reconcile, it's the 0006 with a residual.
Did i do it wrong?
Thanks

**Comment by pedrobaeza** [comment]
Odoo Version?

Please reproduce the same issue on runbot and put the exact steps followed.

**Comment by qpeyramale** [comment]
Sorry, i did this on runbot.odoo-community.org , odoo v10

- Creation of 3 invoices with the same partner , invoice line and amounts with payment mode SEPA Direct Debit of customers
- Creation of the Debit order , adding the lines via Create payment lines from journal items button
- Edit one line with a less amount
- Validation of the Debit order

**Comment by pedrobaeza** [comment]
I confirm that the bug is present. You can check it in http://3301825-10-0-3fe337.runbot1.odoo-community.org/web#id=2&view_type=form&model=account.payment.order&menu_id=185&action=260

@alexis-via I think the problem is here:

https://github.com/OCA/bank-payment/blob/3fe337e1d07e40edbc73dfb1c522f4dbc9c3cb9a/account_payment_order/models/bank_payment_line.py#L155-L157

It's not taking into account the amount entered on each line, just reconciling against the counterpart, so Odoo makes the reconciliation at its taste. And I'm seeing also another potential problem: if you put several partial amounts in several invoices, the mess will be bigger.

Can you please take a look?

**Comment by StefanRijnhart** [comment]
It sounds as if this is a consequence of the setting 'Group Transactions in Payment Orders' on the payment mode. Did you leave this setting to its default active value, and, if you disable it does that solve your problem?

**Comment by pedrobaeza** [comment]
What you propose is a workaround, but it should be handled on both cases.

**Comment by StefanRijnhart** [comment]
That is a matter of opinion. The option 'group transactions in payment orders' results in a single amount being transferred. Look at it from the receivers side, how is the recipient of the amount supposed to know that the amount represents three half paid invoices instead of two paid invoices and one remaining? I think the current behaviour as I asssumed above would be defendable.
