### ISSUE TITLE
[9.0] account_payment_mode: Migration to 9

### ISSUE THREAD

**Issue by rousseldenis** [OCA/bank-payment#494]
@alexis-via As I see, payment.mode existed in v8, but no more in v9. That's why account_payment_mode was created.

But why not having created a migration script for existing data (from v8 to 9) ? Is there a reason?

**Comment by alexis-via** [comment]
This migration script exists and works, but I can't locate it exactly...

**Comment by pedrobaeza** [comment]
Here you have it. It's impossible to get a perfect migration due to the total different module and data structure, but it's very good right now: https://github.com/OCA/bank-payment/tree/9.0/account_payment_order/migrations/9.0.1.0.0

**Comment by rousseldenis** [comment]
@pedrobaeza Nice.
I'm wondering why this is not present in v10 branch too ?

Am I missing something or when migrating, let OpenUpgrade migrates Odoo, then put yourself on final branch version and upgrade other modules (OCA, customs)

**Comment by pedrobaeza** [comment]
Because there's no changes from v9 to v10. You have to pass over each version, so migrating from v8 to v9 forces you to migrate with all the existing OCA addons in version 9. On contrary, the maintenance and possible side effects on accumulated migration scripts will be a hell.

**Comment by sbidoul** [comment]
@pedrobaeza when people use the Odoo migration service, they go in one step ie from 8 to 10. So they have no chance to install and migrate OCA addons on 9.

So I think we should keep the 9 migration scripts on the 10 branch (and so on).

We cannot guarantee they will all work, especially migration script that rely on the orm. But most will just work, at and least we show a starting point.

I also agree maintenance is not easy, but it's not harder than back/forwarding bug fixes across versions.

So I'd like to propose a couple of PR to add the 9 migrations on the 10 and 11 branches of this project.

**Comment by pedrobaeza** [comment]
Sorry, but definitively not. OpenUpgrade clearly states that you should go on each version, and the module and migration scripts is already on version 9. The only thing you have to do is to put that addons on your temp 9.0 migration. It's very easy, and the opposite means a total chaos.

**Comment by sbidoul** [comment]
@pedrobaeza can you take the time to re-read my comment above? I'm not talking about an OpenUpgrade scenario here, I'm in a situation where I receive a database migrated from 8 to 10 by Odoo SA. I don't have a chance to act on the intermediary 9.0 step. What am I supposed to do in such a case?

Here is another scenario:
- a 8.0 database with mis_builder 8.0.1.0.0 installed
- mis_builder 8.0.2.0.0 has been relased with a migration script, but never installed on that database
- there is no migration script from 8.0.2.0.0 to 9.0.1.0.0, because none is necessary
- customer migrates to Odoo 9 with OpenUpgrade or not, it does not matter

If the 8.0.2.0.0 migration script was not present in the 9.0 branch (or 9.0.1.0.0 distribution on apps.odoo.com), the customer would never have a chance to run the migration script.

So we must never remove migration scripts when creating a new versions of a module, be it for the same Odoo series or a different one.

**Comment by pedrobaeza** [comment]
If you have such case from Odoo, then you should deal with that extra scripts on your end, or proposing them again after checking/fixing them for properly work, but not to keep them when migrating modules.

A lot of things will fail for sure because they rely on the data layout of the intermediate version, not the version you want to run on. Starting from all the calls to the wildcard method from openupgradelib, `get_legacy_name`, that will return invalid names, continuing from the already mentioned ORM methods, and ending with several migration mechanisms that rely on the method followed by OpenUpgrade, but unknown on the Odoo blackbox side, we have a 99% chance of this to fail.

I advise you to follow the OpenUpgrade path.

**Comment by rousseldenis** [comment]
I would say that if I follow OCA module migration how-to, we have to get commit history from previous version, so I a suppose most of modules have previous migration scripts on higher branch version yet... And as @sbidoul said, you are not necessarily aware of previous version upgrade scenario. If you can rely on intermediate upgrade scenario scripts, it is easier. I think we have to be clear on that way of doing things on both sides (OpenUpgrade and migration scripts branches existence)

**Comment by pedrobaeza** [comment]
If you read carefully the migration how-to (https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#tasks-to-do-in-the-migration), you'll find:

> * Remove any possible migration script from previous version.

This step was added 3 versions ago because there were already problems with scripts from N - 2 version living in that version.

**Comment by rousseldenis** [comment]
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0/ab99a10c12f99728cbea140b523509704ed923ee

OK, but this was quite new. I agree I was not aware of that.

**Comment by rousseldenis** [comment]
@pedrobaeza Could you point the discussion or PR about this change?

**Comment by pedrobaeza** [comment]
There's no possibility of PRs against Wiki. This was motivated by several issues pointed about errors updating/installing modules and their corresponding PRs removing obsolete migration scripts, but I don't even remember where they were located.

**Comment by rousseldenis** [comment]
OK, that discussion should have been done as maybe some particular bugs(that maybe could be resolved locally) leaded to a general way of doing things...

I just try to lead to a clear way to unpainful migration solutions and limit uncovered (and hidden) code.

**Comment by elicoidal** [comment]
> There's no possibility of PRs against Wiki. 

Wiki is nice and easy but would not it be a good idea to create a docs folder?

**Comment by pedrobaeza** [comment]
> Wiki is nice and easy but would not it be a good idea to create a docs folder?

This will need another site for hosting the rendered documentation + links to it, so it's less convenient.
