### ISSUE TITLE
[10.0] direct debit payment creation is blocking deliveries (stock picking) due to lock on SO invoice status

### ISSUE THREAD

**Issue by jbaudoux** [OCA/bank-payment#588]
I found out this issue in v10. I haven't investigated yet. This is based on DB lock table analysis.

A delivery (stock picking) needs to update the SO line delivered qty and the SO invoice_status.
The payment order (domiciliation) creation is currently a long process that takes time if you have lot of invoices. I don't know yet for what reason but it seems it's fetching data on SO that prevents SO invoice_status to be changed while the process is running.
The delivery transaction is locked waiting for the update to be executed. No concurrent access error is raised, probably because only the delivery wants to update the record while the payment order only read it? So the update transaction is marked as locked in DB and will wait for the payment order to be finished. If the payment order takes 1h to execute, the delivery will be locked for 1h also.

Here is I think a scenario:
1 SO with 2 lines. 1 line is delivered and invoiced. A payment order is created for that invoice. The second line is delivered. This transaction is locked.

**Comment by pedrobaeza** [comment]
Check any related field with not `readonly=True` . I'm pretty sure the problem is that.

**Comment by guewen** [comment]
After analysis, the issue is this:

* when generated2uploaded is processed in a payment order (inbound), it reconciles the move lines
* when these move lines come from sales/invoices, the reconciliation will update the`qty_invoiced` computed (stored) field, locking the row with an Exclusive Lock
* when the payment order contains hundreds of lines, overall the reconciliation is pretty slow and locks every touched account moves and sale order lines for the whole duration

I added some indexes (https://github.com/OCA/bank-payment/pull/590) which help a bit in the payment orders operations but won't resolve the reconciliations' problem. Perhaps some improvements could be done in the reconciliation methods too.

I wrote a small addon extending `account_payment_order` that extract the calls `AccountMoveLine.reconcile()` to jobs using https://github.com/OCA/queue. I think it would be interesting to propose its inclusion to the OCA. Thoughts?

Then, should it be in the same repository than `account_payment_order`?

**Comment by sbidoul** [comment]
@guewen @ThomasBinsfeld has also written an addon to jobify the payment order process. Maybe you can both compare what you have done? This is definitely worth an OCA addon.

**Comment by pedrobaeza** [comment]
I already did this in 8.0 in https://github.com/OCA/bank-payment/tree/8.0/account_payment_transfer_reconcile_batch

What is weird that the invoiced_qty is updated on that event... Maybe incorrect depends?

**Comment by guewen** [comment]
@pedrobaeza Didn't think about why it's called, I'll check, it could totally be a specific code. I'll report there once I found out.

Here's what I did for extracting the reconciliation as jobs (copy-pasted from our project for now without OCA adaptations) https://github.com/OCA/bank-payment/pull/596

**Comment by guewen** [comment]
@pedrobaeza The `qty_invoiced` depends on `invoice_lines.invoice_id.state`. When the entries are reconciled, the invoice changes from `open` to `paid`, trigger the computed field. At this point, the `qty_invoiced` values should not change, but AFAIK the ORM will issue an UPDATE in database anyway even if the computed value is the same.

https://github.com/odoo/odoo/blob/8a84f96641c6f0330a420ad0943c42ff24a0f4f1/addons/sale/models/sale.py#L595-L611

**Comment by gurneyalex** [comment]
@guewen maybe we could propose a patch on Odoo with the last line adding a check  such as

```
if float_compare(qty_invoiced, line.qty_invoiced, precision_rounding=line.product_uom.rounding) != 0:
    line.qty_invoiced = qty_invoiced
```

This could probably be merged in the supported versions of Odoo without harm.

**Comment by guewen** [comment]
> with the last line adding a check such a

The value of the computed field is reset before calling the compute function, so at this point `qy_invoiced` is always 0.

**Comment by pedrobaeza** [comment]
@guewen thanks for the insight about the compute method. Maybe is it an Odoo bug and that depends shouldn't be there?
