### ISSUE TITLE
[12.0] [RFC] Banking Mandate: unique reference at validation

### ISSUE THREAD

**Issue by ThomasBinsfeld** [OCA/bank-payment#592]
It's currently possible to import a mandate with no reference and validate it.

What about making the `unique_mandate_reference` readonly (in Python code, not only in views) and generating the reference at validation instead of creation (closer than what is done on invoices) + a constraint making the reference required in other states than draft.

**Comment by sbidoul** [comment]
@ThomasBinsfeld short term you could create a mandate id if unique_mandate_reference has a falsy value in vals [here](https://github.com/OCA/bank-payment/blob/c54bf6ca5412d888a58bc4fa7f74128b63e30d1b/account_banking_mandate/models/account_banking_mandate.py#L186).

Another improvement is to use '/' instead of 'New', as it is language neutral and used elsewhere for similar things in Odoo.
