### ISSUE TITLE
bank-payment/account_payment_order openupgradelib external dependency not declared

### ISSUE THREAD

**Issue by uolaizola** [OCA/bank-payment#704]
Good morning,

Module bank-payment/account_payment_order has an external dependency with openupgradelib but it is not declared in the __manifest__ file. The dependency was introduced in the '19fc8afb390336b35e1d2f7844bf9c60ff19229c' commit within the migration file.

When the module is installed and the dependency is not resolved it crashes, so it would be appreciated to add it in the manifest file.

Regards,
Ugaitz

**Comment by ValentinVinagre** [comment]
Hi @uolaizola ,
I think "openupgradelib" library always needs to be installed in all deployments, because any modules could contain migration scripts.
"openupgradelib" is a "base" external dependency and setting this dependency in "all modules", wouldn't be good working practices.

@pedrobaeza what you think about that?

**Comment by pedrobaeza** [comment]
Yes, that library is needed for migrations/updates, not for the module itself, and thus it's not declared. As a rule, if you use OCA, and you update source code, install always that library, but can't be declared as a hard library dependency because we will have the chicken-egg problem, as if you introduce it as mandatory, you are breaking the same your DB and even worse, loading but having problems at UI level. That's why it's better to not break but avoid update.

Closing due to the stated above.
