### ISSUE TITLE
Question : what's the conceptual difference between 'account.payment.line' and 'account.payment' ?

### ISSUE THREAD

**Issue by alexAubin** [OCA/bank-payment#934]
Dear OCA developers,

My team is currently using the base Odoo payment workflow + the enterprise batch payment module which in particular allows to generate SEPA PAIN XML files (at least for the provider payment/transfert part)

We are therefore very much interested in those OCA modules to move away from enterprise ;)

I'm trying to understand the models involved and am confused by the `account.payment.line` module and what's the conceptual difference (or is it just legacy?) compared to `account.payment`. Same question for `account.payment.order` vs `account.payment.batch` (from enterprise?).

In particular, as my team is already using the `account.payment` UIs I would appreciate if there's any trick to bind "regular" `account.payment` to those modules. Moreover we have specific business logic implemented on `account.payment` to handle analytic information.

Do you think it is worth looking into binding the PAIN XML generation logic to `account.payment`, or is it way too tight-coupled to `account.payment.line` ?

Thanks in advance for anybody that can provide insight ! (Hopefully this is the right place to ask this kind of question)

Cheers

Alex

**Comment by TeoGoddet** [comment]
I think this is a possible but non trivial move. account.payment.line and account.payment are very similar concept. 
It would be nice to be able to have account.payment getting paid by payment order.

But then we would rely on odoo SA not too modify account.payment too much or we would have painful migrations.
We would also need to add a feature to generate payment from the invoices

I'm curions on how are you generating your account.payment now ? (for invoice payment)

Some people are using odoo without enterprise licence, that's why some feature are present twice such as account.payment.order vs account.payment.batch

**Comment by pedrobaeza** [comment]
This is an historical question and it comes from version 9, where Odoo `account.payment` was less way sophisticated than now. We needed to express individual operations that corresponds to one AR/AP journal item, with the proper bank account and amount attached, and that's why the `account.payment.line`.

Then, you validate the payment order, and `bank.payment.line` are created, that can proceed from one or more `account.payment.line`.

There's in the roadmap to switch from `bank.payment.line` to `account.payment` objects and let Odoo to do the rest of the work when posting the order, but not yet done. `account.payment.line` should remain anyways for storing information that is not kept in any other place (like mandate and bank account).

**Comment by pedrobaeza** [comment]
I did the conversion in #979. Please review it.
